### ISSUE TITLE
[Windows] Installed launcher opens a separate taskbar entry for the running app

### ISSUE THREAD

**Issue by nerdstep** [blackboardsh/electrobun#514]
## Summary

On Windows, launching an installed Electrobun app from its pinned shortcut creates a second taskbar entry instead of associating the running window with the pinned launcher.

The pinned shortcut displays the application’s branded icon. After clicking it:

- The pinned icon remains inactive.
- A second running taskbar button appears.
- The second button uses the Bun/default runtime icon and appears blurry.

This occurs with an installed stable build, so it is not a dev/stable channel distinction.

## Environment

- Windows 11
- Electrobun 1.18.1
- Bun 1.3.14
- Native WebView2 renderer
- Installed stable build
- Custom chrome using `titleBarStyle: "hidden"`

## Configuration

```ts
export default {
  app: {
    name: "Manifesto",
    identifier: "dev.manifesto.app",
    version: "0.1.0",
  },
  build: {
    win: {
      icon: "assets/app-icon.ico",
    },
  },
}
```

The window is created with:

```ts
new BrowserWindow({
  title: "Manifesto",
  url: "views://mainview/index.html",
  frame,
  rpc,
  titleBarStyle: "hidden",
})
```

## Steps to reproduce

1. Build a stable Windows package.
2. Install the application.
3. Pin its installed shortcut to the taskbar.
4. Close the application.
5. Click the pinned taskbar icon.
6. Observe that Windows adds a separate running taskbar button rather than grouping the window with the pinned icon.

## Expected behavior

The installed shortcut, launcher process, Bun-hosted native window, and taskbar button should share the identity derived from `app.identifier`.

Clicking the pinned icon should turn that same icon into the running taskbar button.

## Actual behavior

The launcher shortcut and running native window are treated as different applications. The runtime window also falls back to the Bun/default icon.

This is consistent with the installed shortcut and running process/window not sharing an explicit Windows AppUserModelID. Changing the native window icon alone does not correct the taskbar grouping.

## Related packaging issue

The `build.win.icon` path also fails to resolve Electrobun’s packaged `rcedit`:

```text
Warning: Failed to embed icon into launcher.exe: ResolveMessage: Cannot find module 'D:\a\electrobun\electrobun\package\node_modules\rcedit\package.json' from 'B:\~BUN\root\electrobun'

Warning: Failed to embed icon into bun.exe: ResolveMessage: Cannot find module 'D:\a\electrobun\electrobun\package\node_modules\rcedit\package.json' from 'B:\~BUN\root\electrobun'

Warning: Failed to embed icon into Windows installer: ResolveMessage: Cannot find module 'D:\a\electrobun\electrobun\package\node_modules\rcedit\package.json' from 'B:\~BUN\root\electrobun'
```

That packaging failure is already tracked by #429 and #235. This report is specifically about runtime/shortcut identity and taskbar grouping.

#458 may also be relevant because it reports the Windows wrapper falling back from its custom window class.

## Screenshots

<img width="146" height="148" alt="Image" src="https://github.com/user-attachments/assets/57efa090-7dde-4d8f-b85e-4358e2edc692" />

The attached screenshot shows the branded pinned shortcut and separate running taskbar button beside one another.

**Comment by GolubNick** [comment]
I managed to replace the default bun.exe icon with a custom icon.
However, the custom icon appears blurry after being embedded into bun.exe even though the original icon is high resolution.
The launcher.exe uses the same icon with the same resolution and it looks perfectly fine there. The issue only appears with the icon embedded into bun.exe.

Confirming on Electrobun 1.18.1 / Windows 11
